# permissions for end users to edit kubesharks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubeshark-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ks-operator
    app.kubernetes.io/part-of: ks-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeshark-editor-role
rules:
- apiGroups:
  - apps.kubeshark.co
  resources:
  - kubesharks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubeshark.co
  resources:
  - kubesharks/status
  verbs:
  - get
