# Kubeshar Operator for kubeshark.co - API Traffic Analyzer
# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/ks-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard
